on: [push]

jobs:
  2faCheck:
    runs-on: ubuntu-latest
    name: check for 2fa enabled on all members of the org
    steps:
      - name: ðŸš€
        uses: 100Automations/action-check-org-members-enable-mfa@main
        env:
          GITHUB_ORG: 100Automations
          GITHUB_ORG_OWNER_TOKEN: ${{ secrets.GITHUB_ORG_OWNER_TOKEN }}
